### ISSUE TITLE
Are you sure you want others contributing to this?

### ISSUE THREAD

**Issue by thisisrajneel** [madhurajayashanka/portfolio#3]
This repo is tagged with the hacktoberfest tag and I see it's your portfolio website. Are you sure you want contributions to it? Because it's not common. Anyway, if that is the case, I'd like to contribute.

**Comment by madhurajayashanka** [comment]
> This repo is tagged with the hacktoberfest tag and I see it's your portfolio website. Are you sure you want contributions to it? Because it's not common. Anyway, if that is the case, I'd like to contribute.

You're warmly welcome to add new features.

**Comment by thisisrajneel** [comment]
I have opened a pull request for a small change I made. I couldn't find much to add on, because you've made a really good portfolio hahaha.
